version: '3.9'

#docker service create \
#  --name=viz \
#  --publish=8080:8080/tcp \
#  --constraint=node.role==manager \
#  --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
#  dockersamples/visualizer
services:
  visualizer:
#    https://github.com/dockersamples/docker-swarm-visualizer
    image: dockersamples/visualizer
    networks:
      - app_network
    ports:
      - "${VISUALIZER_HOST_PORT?:err}:${VISUALIZER_DOCKER_PORT?:err}"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
#      - /var/run/docker.sock:/var/run/docker.sock
networks:
  app_network:
