version: '3.9'

services:
  postgresql:
    image: bitnami/postgresql:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 20s
      timeout: 30s
      retries: 5
    secrets:
      - dbuser-password
      - postgres-password
    networks:
      - app_network
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER?err}
      POSTGRESQL_PASSWORD_FILE: /run/secrets/dbuser-password
      POSTGRESQL_DATABASE: ${POSTGRES_DB?err}
      POSTGRESQL_POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRESQL_LOG_LINE_PREFIX: '%t [%p]: [%l-1] '
      POSTGRESQL_LOG_TIMEZONE: ${TIME_ZONE}
      PGADMIN_PORT: ${PGADMIN_PORT?err}
      TZ: ${TIME_ZONE}
      LANG: 'en_US.UTF-8'
      LANGUAGE: 'en_US:en'
    expose:
      - "${POSTGRES_PORT?err}"
#    ports:
#      - "${POSTGRES_PORT?err}:${POSTGRES_PORT?err}"
    tty: true
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.purpose==database"
      restart_policy:
        condition: on-failure
    volumes:
      - ./data/postgresql:/bitnami/postgresql
      - ./log/postgresql:/opt/bitnami/postgresql/logs
  django:
    image: alexzolotarev/bakerydemodjango:0.1.0
    secrets:
      - dbuser-password
      - django-secret
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:${DJANGO_DOCKER_PORT?err}/"
      interval: 20s
      timeout: 30s
      retries: 3
      start_period: 60s
    networks:
      - app_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER?err}
      DBUSER_PASSWORD_FILE: /run/secrets/dbuser-password
      POSTGRES_DB: ${POSTGRES_DB?err}
      POSTGRES_PORT: ${POSTGRES_PORT?err}
      APP_NAME: ${APP_NAME?err}
      VIRTUAL_PROTO: uwsgi
      DJANGO_SECRET_KEY: /run/secrets/django-secret
      TZ: ${TIME_ZONE}
      DJANGO_DOCKER_PORT: ${DJANGO_DOCKER_PORT?err}
      NGINX_UWSGI_PORT: ${NGINX_UWSGI_PORT?err}
    depends_on:
      postgresql:
        condition: service_healthy
    deploy:
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.purpose==web"
      restart_policy:
        condition: on-failure
    volumes:
      - media-root:/code/${APP_NAME}/media/images
      - web-root:/code/${APP_NAME?err}/collect_static
      - ./media/original_images:/code/${APP_NAME?err}/media/original_images
      - ./config/uwsgi.ini:/code/uwsgi.ini
      - ./log/uwsgi:/var/log/uwsgi
    #      - tmp:/tmp
    expose:
      - "${NGINX_UWSGI_PORT?err}"
#    ports:
#      - "${DJANGO_HOST_PORT?err}:${DJANGO_DOCKER_PORT?err}"
    logging:
      options:
        max-file: "5"
        max-size: "5m"
    entrypoint: [ "/code/docker-entrypoint.sh" ]
    command: [ "/venv/bin/uwsgi", "--strict", "--show-config", "./uwsgi.ini" ]
  nginx:
    image: nginx
    environment:
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/templates
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
      APP_NAME: ${APP_NAME?err}
      APP_URL: ${APP_URL?err}
      NGINX_UWSGI_PORT: ${NGINX_UWSGI_PORT?err}
      NGINX_HOST_PORT: ${NGINX_HOST_PORT?err}
      NGINX_DOCKER_PORT: ${NGINX_DOCKER_PORT?err}
      VISUALIZER_HOST_PORT: ${VISUALIZER_HOST_PORT?err}
      PGADMIN_PORT: ${PGADMIN_PORT?err}
      TZ: ${TIME_ZONE}
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - app_network
    ports:
      - "${NGINX_HOST_PORT?err}:${NGINX_DOCKER_PORT?err}"
    logging:
      options:
        max-file: "5"
        max-size: "5m"
    volumes:
      - ./config/app-nginx.conf.template:/etc/nginx/templates/app-nginx.conf.template
      - ./secrets/swarm.htpasswd:/etc/nginx/conf.d/swarm.htpasswd
      - media-root:/code/${APP_NAME}/media/images
      - web-root:/code/${APP_NAME}/collect_static
      - ./log/nginx:/var/log/nginx/
    # we need it uncomment to unix sock only
    ##      - tmp:/tmp:ro
    depends_on:
      django:
        condition: service_healthy
    deploy:
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.purpose==web"
      restart_policy:
        condition: on-failure
volumes:
  web-root:
  media-root:
  data:
  log:
#  tmp:
#    driver: local
secrets:
  dbuser-password:
    file: secrets/dbuser_password.txt
  #    external: true
  postgres-password:
    file: secrets/postgres_password.txt
  #    external: true
  django-secret:
    file: secrets/django_secret.txt
#    openssl rand -base64 40 | docker secret create django-secret -
#    external: true
networks:
  app_network: